//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrầnThếTường_9157_Bt_ql_banhang
{
    public partial class giohang_xoasua1
    {
    }
}
